<a href="https://colab.research.google.com/github/18K41A0565/NLP/blob/main/Assignemnt_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
string='''paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs.  This  is because paragraphs show a reader where the subdivisions of an essay begin 
and end, and thus help the reader see the organization of the essay and grasp its main points.

Paragraphs  can  contain  many  different  kinds  of  information.  A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point.  It  might  describe  a  place like kolkata,  character,  or  process;  narrate  a series of events; compare or contrast two or more things; classify items into 
categories;  or  describe  causes  and  effects.  Regardless  of  the  kind  of information they contain, all paragraphs share certain characteristics. One 
of the most important of these is a topic sentence.'''

print(string)

paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.  Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs.  This  is because paragraphs show a reader where the subdivisions of an essay begin 
and end, and thus help the reader see the organization of the essay and grasp its main points.

Paragraphs  can  contain  many  different  kinds  of  information.  A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point.  It  might  describe  a  place like kolkata,  character,  or  process;  narrate  a series of events; compare or contrast two or more things; classify items into 
categories;  or  describe  causes  and  effects.  Regardless  of  the  kind  of information they contain, all paragraphs share certain characteristics. One 
of the most important of these is a topic sentence.


In [5]:
import numpy as np
import nltk
import re
import gensim
from nltk.corpus import stopwords
from gensim.models import Word2Vec
from gensim import corpora,models,similarities
from nltk.tokenize import PunktSentenceTokenizer
nltk.download('punkt')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [6]:
#code to convert paragraph to sentences
def essay_to_sentences(paragraph):
    tokenizer = nltk.data.load('tokenizers/punkt/english.pickle')
    raw_sentences = tokenizer.tokenize(paragraph.strip())
    sentences = []
    for raw_sentence in raw_sentences:
        if len(raw_sentence) > 0:
            sentences.append((raw_sentence))
    return sentences

sentences=essay_to_sentences(string)

sentences

['paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic.',
 'Almost  every  piece  of  writing  you  do  that  is \nlonger  than  a  few  sentences  should  be  organized  into  paragraphs.',
 'This  is because paragraphs show a reader where the subdivisions of an essay begin \nand end, and thus help the reader see the organization of the essay and grasp its main points.',
 'Paragraphs  can  contain  many  different  kinds  of  information.',
 'A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a \ngeneral  point.',
 'It  might  describe  a  place like kolkata,  character,  or  process;  narrate  a series of events; compare or contrast two or more things; classify items into \ncategories;  or  describe  causes  and  effects.',
 'Regardless  of  the  kind  of information they contain, all paragraphs share certain characteristics.',
 'One \nof the most important of these is a topic s

In [7]:
wordvecs=[nltk.word_tokenize(sent) for sent in sentences]
from nltk.corpus import stopwords
nltk.download('stopwords')
stops=list(set(stopwords.words("english")))


for i in wordvecs:
    for j in i:
        if j in stops:
            i.remove(j)
        elif len(j)==1:
            i.remove(j)

model=gensim.models.Word2Vec(wordvecs,min_count=1)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [8]:
#printing vector form of word 'paragraph'
model['paragraph']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `__getitem__` (Method will be removed in 4.0.0, use self.wv.__getitem__() instead).
  


array([ 1.2344383e-03,  2.1240513e-03, -1.4935071e-03,  7.0213020e-04,
       -2.7302920e-03, -4.0515757e-04, -1.4761484e-03,  9.6753967e-04,
       -1.2539912e-03,  5.9788197e-04, -2.4501723e-03, -3.2714594e-03,
        2.4968304e-03,  2.1226180e-03, -3.4806936e-03, -2.9451752e-03,
       -1.6139792e-03,  3.3010151e-03,  3.4834044e-03,  3.5035140e-03,
       -2.2858204e-03, -3.4318776e-03,  3.6568270e-04, -1.8123043e-03,
        9.4778487e-04, -1.5571102e-03, -3.3948058e-03, -4.3436191e-03,
       -3.4022103e-03,  4.8639672e-03,  1.5430674e-03, -3.5541032e-03,
        2.6810949e-03,  4.7034435e-03,  4.1537830e-03, -3.9938060e-03,
       -2.9909925e-03, -2.5144123e-04, -3.5197294e-04,  3.9549177e-03,
       -1.9912422e-03,  1.5111066e-03, -4.7027571e-03, -1.7798570e-03,
       -2.3228487e-03, -1.9020236e-03, -9.7181340e-04, -2.8998705e-03,
        2.8763472e-03, -4.9481662e-03,  1.6592331e-03, -2.0081229e-03,
        1.1978630e-03,  5.2911753e-04,  1.3904788e-03,  1.9157181e-03,
      

In [9]:
#finding similar words of word 'sentence' in given paragraph
model.most_similar('sentence')

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: DeprecationWarning: Call to deprecated `most_similar` (Method will be removed in 4.0.0, use self.wv.most_similar() instead).
  


[('sentences', 0.1918172538280487),
 ('and', 0.1862972378730774),
 ('character', 0.1840035617351532),
 ('causes', 0.17626433074474335),
 ('kind', 0.15809129178524017),
 ('characteristics', 0.15194189548492432),
 ('information', 0.1460990309715271),
 ('is', 0.1433011293411255),
 ('process', 0.10735267400741577),
 ('This', 0.1042013019323349)]

In [10]:
#importing USE model
import tensorflow_hub as hub
use= hub.load("https://tfhub.dev/google/universal-sentence-encoder/4")
#converting to vectors
embeddings=use(sentences)
print(embeddings)

INFO:absl:Using /tmp/tfhub_modules to cache modules.


tf.Tensor(
[[ 0.0130397  -0.02448178  0.05377616 ... -0.08659647  0.01437556
   0.04036802]
 [ 0.02902018 -0.00415597  0.07664446 ... -0.06830524 -0.00835191
   0.04397805]
 [ 0.07023076 -0.02952436  0.04878015 ... -0.06741599  0.02838855
   0.06126793]
 ...
 [ 0.04487116 -0.0484449   0.05696819 ... -0.06665879  0.03268223
   0.03346183]
 [ 0.04141247  0.0258891  -0.00625629 ... -0.0216299   0.00910816
   0.03623573]
 [ 0.00255486 -0.05832284  0.01486255 ... -0.09906971 -0.07840379
   0.06731212]], shape=(8, 512), dtype=float32)


In [11]:
print("shape= ",embeddings[0].shape)
#each sentence is converted into vector having 512 values
print("The sentence: ",sentences[0],"\n is converted as : \n{}".format(embeddings[0]))

shape=  (512,)
The sentence:  paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 is converted as : 
[ 0.0130397  -0.02448178  0.05377616  0.09029772 -0.00281371 -0.01281828
  0.03285866  0.01635625 -0.06859536  0.06464799 -0.00420633 -0.00475263
 -0.0616823   0.02333648 -0.0740284  -0.09213066 -0.04730163  0.03868826
 -0.09117856 -0.0531873   0.0045717   0.06571639 -0.00334152  0.05408446
 -0.02477303  0.02715091 -0.02349129 -0.05725229 -0.01281677 -0.02824831
  0.08104642 -0.01898845  0.00283233 -0.01492393 -0.0671662   0.01855971
  0.05093659  0.0259113   0.01541285  0.02317855  0.01918534  0.04582307
  0.03908791  0.03328896  0.05890476  0.03568182  0.00344607 -0.05167899
 -0.03721966  0.02001154  0.00619585  0.05630827  0.00328268 -0.02715196
 -0.04551012 -0.01019349  0.01659425  0.05470299  0.0246249   0.02216954
 -0.00490041 -0.03435751  0.05740487  0.06339793  0.05196239  0.00615372
  0.04076186 -0.02079652  0.060018

In [12]:
#importing sentencebert model
bert = hub.KerasLayer("https://tfhub.dev/google/nnlm-en-dim128/2")
embeddings2=bert(sentences)
print(embeddings2)

tf.Tensor(
[[ 0.5779494   0.02082791  0.09225276 ...  0.1423439   0.0289949
  -0.15707761]
 [ 0.5166956   0.00863559  0.13047293 ...  0.06873029  0.04432377
   0.02298209]
 [ 0.7741569   0.20155099 -0.06426485 ... -0.15599789  0.10988081
   0.10273374]
 ...
 [ 0.49916965 -0.00334622  0.08184471 ...  0.05571959 -0.09832127
  -0.04315813]
 [ 0.2909918   0.06627773  0.08403497 ... -0.10017543 -0.11646989
   0.00867226]
 [ 0.3799187  -0.05745781  0.09742597 ...  0.0461409  -0.07855327
   0.03973798]], shape=(8, 128), dtype=float32)


In [13]:
print("shape=",embeddings2[0].shape)
#each sentence is converted into vector having 128 values
print("The sentence: ",sentences[0],"\n is converted as : \n{}".format(embeddings2[0]))

shape= (128,)
The sentence:  paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 is converted as : 
[ 5.77949405e-01  2.08279062e-02  9.22527611e-02  4.76201549e-02
 -1.17820695e-04 -7.91035891e-02 -9.09532905e-02 -1.96999479e-02
 -1.82167172e-01  1.82781354e-01  1.78407803e-02 -1.36595681e-01
 -1.20970421e-01  3.03527750e-02 -1.55288994e-01 -3.65624130e-02
 -8.87916684e-02  1.18960990e-02 -2.42571995e-01  1.40147313e-01
  6.29373714e-02  1.13711674e-02  2.64876569e-03 -7.81569928e-02
  5.36865816e-02 -9.01894644e-02 -6.66456744e-02 -4.82053608e-02
 -3.14572081e-02  3.31105255e-02  2.45857425e-03 -5.02937846e-02
 -4.58035916e-02 -2.23965168e-01 -1.51718352e-02 -2.75546517e-02
  5.16168959e-02 -1.21403374e-01 -2.82064285e-02  2.14980636e-02
  9.37252939e-02 -7.97212273e-02  2.16491118e-01 -4.78220843e-02
 -5.53186908e-02  1.48325905e-01  1.11704050e-02 -1.39561430e-01
 -8.59184787e-02 -3.15666497e-02 -7.05443416e-03 -1.229588

In [14]:
!pip install "tensorflow>=2.0.0"
!pip install --upgrade tensorflow-hub

In [15]:
import tensorflow_hub as hub
import tensorflow.compat.v1 as tf
tf.disable_eager_execution()
#1024 sized vectors
elmo=hub.Module("https://tfhub.dev/google/elmo/3",trainable=True)
embeddings=elmo(
    sentences,
    signature="default",
    as_dict=True)["elmo"]
init=tf.initialize_all_variables()
sess=tf.Session()
sess.run(init)
print("\n\n")
print(sess.run(embeddings[0]))
print("shape=",embeddings[0].shape)

INFO:tensorflow:Saver not created because there are no variables in the graph to restore


INFO:tensorflow:Saver not created because there are no variables in the graph to restore


Instructions for updating:
Use `tf.global_variables_initializer` instead.


Instructions for updating:
Use `tf.global_variables_initializer` instead.





[[ 0.12622021  0.43023553  0.4043871  ...  0.22031897  0.26976916
   0.46307242]
 [-0.0062146   0.333897    0.10469673 ... -0.6755089   0.25390008
   0.654027  ]
 [ 0.00899898  0.4038667   0.13564664 ... -0.04539599  0.19543737
  -0.34905794]
 ...
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]
 [-0.02840841 -0.04353216  0.04130163 ...  0.02583168 -0.01429836
  -0.01650422]]
shape= (32, 1024)


In [16]:
import torch
import transformers

In [17]:
gptokenizer=transformers.GPT2Tokenizer.from_pretrained('gpt2-large')
model=transformers.GPT2LMHeadModel.from_pretrained('gpt2-large')
output=gptokenizer.encode(string,add_special_tokens=False,return_tensors="pt")

In [18]:
print("shape=",output.shape)
output

shape= torch.Size([1, 256])


tensor([[20360,   318,   257,  2168,   286, 13439,   326,   389,  8389,   290,
         24870,    11,   290,   389,   477,   220,  3519,   220,   284,   220,
           257,   220,  2060,   220,  7243,    13,   220, 16699,   220,   790,
           220,  3704,   220,   286,   220,  3597,   220,   345,   220,   466,
           220,   326,   220,   318,   220,   198,  6511,   263,   220,   621,
           220,   257,   220,  1178,   220, 13439,   220,   815,   220,   307,
           220,  8389,   220,   656,   220, 23549,    13,   220,   770,   220,
           318,   780, 23549,   905,   257,  9173,   810,   262, 45944,  3279,
           286,   281, 14268,  2221,   220,   198,   392,   886,    11,   290,
          4145,  1037,   262,  9173,   766,   262,  4009,   286,   262, 14268,
           290, 13180,   663,  1388,  2173,    13,   198,   198, 10044,  6111,
            82,   220,   460,   220,  3994,   220,   867,   220,  1180,   220,
          6982,   220,   286,   220,  1321,    13,  

In [19]:
import spacy
from spacy import displacy
ner=spacy.load('en')
result=ner(string)

for word in result.ents:
  print(word.text,word.label_)

kolkata PERSON
two CARDINAL
One CARDINAL


In [20]:
spacy.explain('GPE')

'Countries, cities, states'

In [21]:
#better visualisation of entity recognition
displacy.render(result,style="ent",jupyter=True)

In [22]:
# finding named entities of another paragraph
resultss=ner("Cricket was introduced to India by British sailors in the 18th century, and the first cricket club was established in 1792. India's national cricket team did not play its first Test match until 25 June 1932 at Lord's, becoming the sixth team to be granted test cricket status. From 1932 India had to wait until 1952, almost 20 years for its first Test victory. In its first fifty years of international cricket, India didn't gain much success, winning only 35 of the first 196 Test matches it played. The team, however, gained strength in the 1970s with the emergence of players like Gavaskar, Viswanath, Kapil Dev, and the Indian spin quartet.")
for word in resultss.ents:
  print(word.text,word.label_)

India GPE
British NORP
the 18th century DATE
first ORDINAL
1792 DATE
India GPE
first ORDINAL
25 June 1932 DATE
sixth ORDINAL
1932 DATE
India GPE
1952 DATE
almost 20 years DATE
first ORDINAL
its first fifty years DATE
India GPE
only 35 CARDINAL
first ORDINAL
196 CARDINAL
the 1970s DATE
Gavaskar PERSON
Viswanath ORG
Kapil Dev PERSON
Indian NORP


In [23]:
#better visualisation of entity recognition
displacy.render(resultss,style="ent",jupyter=True)

In [24]:
pip install -U sentence-transformers

     |████████████████████████████████| 78 kB 2.6 MB/s 
     |████████████████████████████████| 1.2 MB 11.8 MB/s 
  Created wheel for sentence-transformers: filename=sentence_transformers-2.1.0-py3-none-any.whl size=121000 sha256=b0c4847549dbcd48293b56828c2a3e6f449cf9a50f0e644d9cde890fcc00aa4e
  Stored in directory: /root/.cache/pip/wheels/90/f0/bb/ed1add84da70092ea526466eadc2bfb197c4bcb8d4fa5f7bad
Successfully built sentence-transformers


In [25]:
from sentence_transformers import SentenceTransformer
sbert_model = SentenceTransformer('bert-base-nli-mean-tokens')

Downloading:   0%|          | 0.00/391 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/3.95k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/2.00 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/625 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/122 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/229 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/438M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/399 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [26]:
se_embeddings = sbert_model.encode(sentences)
q1_vec= sbert_model.encode(sentences[0])

#cosine similarity function
#identifies similarity between 2 sentences
def cosine(u, v):
    return np.dot(u, v) / (np.linalg.norm(u) * np.linalg.norm(v))

for sent in sentences:
  sim = cosine(q1_vec, sbert_model.encode([sent])[0])
  #if similarity ==1 => repeated sentence
  #if similarity > 0.6 => similar sentence
  if sim>0.6:
    print("Sentence1 =",sentences[0],"\n \nSentence2=", sent, "\n\nsimilarity = ", sim,end="\n ----------------------------- \n")

Sentence1 = paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 
Sentence2= paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 

similarity =  1.0
 ----------------------------- 
Sentence1 = paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 
Sentence2= Almost  every  piece  of  writing  you  do  that  is 
longer  than  a  few  sentences  should  be  organized  into  paragraphs. 

similarity =  0.64265954
 ----------------------------- 
Sentence1 = paragraph is a series of sentences that are organized and coherent, and are all  related  to  a  single  topic. 
 
Sentence2= A  paragraph could  contain  a  series  of  brief  examples  or  a  single  long  illustration  of  a 
general  point. 

similarity =  0.6779764
 ----------------------------- 
Sentence1 = paragraph is a series of sentences that are or

**QUESTION 4 in PDF**